KMinimalistStyling.definitions = {}
KMinimalistStyling.definitions.complex_elements = {
  {field_name = "font_color", type_name = "color"},
  {field_name = "hovered_font_color", type_name = "color"},
  {field_name = "clicked_font_color", type_name = "color"},
  {field_name = "disabled_font_color", type_name = "color"},
  {field_name = "pie_progress_color", type_name = "color"},
  {field_name = "color", type_name = "color"}
}

KMinimalistStyling.definitions.sugar_elements = {
  {field_name = "width_f", type_name = "number"},
  {field_name = "height_f", type_name = "number"},
  {field_name = "padding", type_name = "number"},
  {field_name = "vertical_padding", type_name = "number"},
  {field_name = "horizontal_padding", type_name = "number"},
  {field_name = "vertical_cell_padding", type_name = "number"},
  {field_name = "horizontal_cell_padding", type_name = "number"},
  {field_name = "title_padding", type_name = "number"},
  {field_name = "title_vertical_padding", type_name = "number"},
  {field_name = "title_horizontal_padding", type_name = "number"},
  {field_name = "margin", type_name = "number"},
  {field_name = "vertical_margin", type_name = "number"},
  {field_name = "horizontal_margin", type_name = "number"},
  {field_name = "extra_margin_when_activated", type_name = "number"},
  {field_name = "extra_vertical_margin_when_activated", type_name = "number"},
  {field_name = "extra_horizontal_margin_when_activated", type_name = "number"},
  {field_name = "spacing", type_name = "number"}
}

KMinimalistStyling.definitions.simple_elements = {
  {field_name = "width", type_name = "number"},
  {field_name = "height", type_name = "number"},
  {field_name = "minimal_width", type_name = "number"},
  {field_name = "maximal_width", type_name = "number"},
  {field_name = "natural_width", type_name = "number"},
  {field_name = "minimal_height", type_name = "number"},
  {field_name = "maximal_height", type_name = "number"},
  {field_name = "natural_height", type_name = "number"},
  {field_name = "top_padding", type_name = "number"},
  {field_name = "right_padding", type_name = "number"},
  {field_name = "bottom_padding", type_name = "number"},
  {field_name = "left_padding", type_name = "number"},
  {field_name = "cell_padding", type_name = "number"},
  {field_name = "top_cell_padding", type_name = "number"},
  {field_name = "right_cell_padding", type_name = "number"},
  {field_name = "bottom_cell_padding", type_name = "number"},
  {field_name = "left_cell_padding", type_name = "number"},
  {field_name = "extra_padding_when_activated", type_name = "number"},
  {field_name = "title_top_padding", type_name = "number"},
  {field_name = "title_right_padding", type_name = "number"},
  {field_name = "title_bottom_padding", type_name = "number"},
  {field_name = "title_left_padding", type_name = "number"},
  {field_name = "top_margin", type_name = "number"},
  {field_name = "right_margin", type_name = "number"},
  {field_name = "bottom_margin", type_name = "number"},
  {field_name = "left_margin", type_name = "number"},
  {field_name = "extra_top_margin_when_activated", type_name = "number"},
  {field_name = "extra_bottom_margin_when_activated", type_name = "number"},
  {field_name = "extra_left_margin_when_activated", type_name = "number"},
  {field_name = "extra_right_margin_when_activated", type_name = "number"},
  {field_name = "horizontal_align", type_name = "string"},
  {field_name = "vertical_align", type_name = "string"},
  {field_name = "horizontally_stretchable", type_name = "boolean"},
  {field_name = "vertically_stretchable", type_name = "boolean"},
  {field_name = "horizontally_squashable", type_name = "boolean"},
  {field_name = "vertically_squashable", type_name = "boolean"},
  {field_name = "single_line", type_name = "boolean"},
  {field_name = "want_ellipsis", type_name = "boolean"},
  {field_name = "stretch_image_to_widget_size", type_name = "boolean"},
  {field_name = "use_header_filler", type_name = "boolean"},
  {field_name = "font", type_name = "string"},
  {field_name = "horizontal_spacing", type_name = "number"},
  {field_name = "vertical_spacing", type_name = "number"},
  {field_name = "clicked_vertical_offset", type_name = "number"}
}